server:
  port: ${PORT:8080}

# Security
token:
  expiration_time: 86400000
  secret: DDEF552222CB580670D7C428E7BAC5584AE930D05B5A20F3582892CE6720A3EB
# Spring Boot configuration
spring:
  application:
    name: reservation
    version: 0.0.1-SNAPSHOT
  liquibase.change-log: "classpath:/db/changelog/master.xml"
  messages:
    basename: i18n.messages
    encoding: UTF-8
  # Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:reservation_db;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "UTC"
#springdoc:
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true
openapi:
  server:
    url: http://localhost:8080
#Logging
logging:
  file:
    path: logs/
    name: logs/app.log
#    max-size: 20MB
#    max-history: 180
#    clean-history-on-start: true
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
        security: ERROR
      hibernate: ERROR
    guru:
      springframework:
        controllers: ERROR
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %-5level [traceId:%X{traceId:-}, clientIp:%X{clientIp:-}] %logger{36} - %msg%n"
#    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: logs/app-%d{yyyy-MM-dd-HH}.%i.log